name: Unit Tests and Documentation Check
on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run Tests
        run: uv run pytest --cov=manufacturing --cov-report=html

      - name: Build docs
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          uv run sphinx-build -b html . _build

      - name: Build wheel file in `dist/`
        run: uv build
